runtime: nodejs10
handlers:
- url: /(.*\..+)$
  secure: always
  redirect_http_response_code: 301
  script: auto
  static_files: dist/\1
  upload: dist/(.*\..+)$
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
  static_files: dist/index.html
  upload: dist/index.html
