on:
  push:
    branches:
      - master
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - uses: actions/gcloud/cli@master
        with:
          args: app deploy --quiet --project=OginoTest ./app.yaml

